<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Editorial Author for Product Analysis Pages
    |--------------------------------------------------------------------------
    |
    | Author attribution for AI-generated editorial content on product pages.
    | This helps establish E-E-A-T signals for Google AdSense compliance.
    | Override in .env with EDITORIAL_AUTHOR_NAME and EDITORIAL_AUTHOR_TITLE
    |
    */
    'editorial' => [
        'author_name'  => env('EDITORIAL_AUTHOR_NAME', 'SMART SHIELD UI Editorial Team'),
        'author_title' => env('EDITORIAL_AUTHOR_TITLE', 'Consumer Protection Analysts'),
        'author_bio'   => env('EDITORIAL_AUTHOR_BIO', 'Our editorial team combines AI analysis with expert oversight to provide unique buying guidance for every product we review. Each editorial piece is generated using our proprietary analysis engine and reflects insights from examining thousands of product reviews.'),
    ],

    /*
    |--------------------------------------------------------------------------
    | Author Information (E-E-A-T Compliance)
    |--------------------------------------------------------------------------
    |
    | Author credentials for Google AdSense E-E-A-T requirements.
    | Each author has verifiable expertise in their respective fields.
    |
    */
    'authors' => [
        'derek-armitage' => [
            'name'        => 'Derek Armitage',
            'role'        => 'Founder & Lead Developer',
            'bio'         => 'Derek Armitage is the founder of Shift8 Web, a Toronto-based web development agency. With over 15 years of experience in software development and data analysis, Derek created SMART SHIELD UI to help consumers identify fraudulent Amazon reviews. He holds expertise in machine learning, natural language processing, and web security. Derek has previously written about e-commerce fraud detection for industry publications and regularly contributes to open-source projects focused on consumer protection.',
            'credentials' => [
                '15+ years software development experience',
                'Founder of Shift8 Web (Toronto)',
                'Machine learning and NLP specialist',
                'Open source contributor',
            ],
            'links' => [
                'website'  => 'https://shift8web.ca',
                'github'   => 'https://github.com/stardothosting',
                'linkedin' => 'https://linkedin.com/in/derekarmitage',
            ],
        ],
        'research-team' => [
            'name'        => 'SMART SHIELD UI Research Team',
            'role'        => 'Consumer Protection Researchers',
            'bio'         => 'The SMART SHIELD UI Research Team consists of data scientists, consumer advocates, and e-commerce specialists dedicated to protecting online shoppers from fraudulent reviews. Our team has collectively analyzed over 40,000 Amazon products and published findings on review manipulation tactics, AI-generated content detection, and consumer protection strategies.',
            'credentials' => [
                '40,000+ products analyzed',
                'Specialized in AI content detection',
                'Consumer advocacy focus',
                'Open-source methodology',
            ],
            'links' => [
                'github' => 'https://github.com/stardothosting/nullfake',
            ],
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Blog Posts
    |--------------------------------------------------------------------------
    |
    | Each post includes: slug, title, description, author_key (references authors above),
    | date, image, keywords, view, reading_time, sources (for E-E-A-T citations),
    | and last_updated for content freshness.
    |
    */
    'posts' => [
        [
            'slug'         => 'how-to-spot-fake-amazon-reviews',
            'title'        => 'How to Spot Fake Amazon Reviews: 10 Warning Signs in 2025',
            'description'  => 'Learn the telltale signs of fake Amazon reviews including AI-generated text, suspicious timing patterns, generic language, and reviewer behavior red flags. Based on analysis of 40,000+ products.',
            'author_key'   => 'derek-armitage',
            'date'         => '2025-12-23',
            'last_updated' => '2026-01-10',
            'image'        => 'https://images.unsplash.com/photo-1484995342839-a9eb42974616?auto=format&fit=crop&w=1200&h=630&q=70',
            'keywords'     => 'fake reviews, amazon reviews, review fraud, ai generated reviews, suspicious reviews, consumer protection',
            'view'         => 'blog.posts.how-to-spot-fake-amazon-reviews',
            'reading_time' => 8,
            'sources'      => [
                'FTC guidelines on endorsements and testimonials',
                'Amazon Community Guidelines',
                'Academic research on review manipulation',
            ],
        ],
        [
            'slug'         => 'psychology-of-fake-reviews',
            'title'        => 'The Psychology Behind Fake Reviews: Why They Work',
            'description'  => 'Understand the psychological tactics used in fake reviews and why consumers fall for them. Analysis of social proof, authority bias, cognitive shortcuts, and manipulation techniques.',
            'author_key'   => 'research-team',
            'date'         => '2025-12-24',
            'last_updated' => '2026-01-10',
            'image'        => 'https://images.unsplash.com/photo-1520607162513-77705c0f0d4a?auto=format&fit=crop&w=1200&h=630&q=70',
            'keywords'     => 'fake review psychology, social proof, consumer behavior, review manipulation, cognitive bias',
            'view'         => 'blog.posts.psychology-of-fake-reviews',
            'reading_time' => 7,
            'sources'      => [
                'Cialdini, R. (2006). Influence: The Psychology of Persuasion',
                'Kahneman, D. (2011). Thinking, Fast and Slow',
                'Journal of Consumer Psychology research',
            ],
        ],
        [
            'slug'         => 'amazon-verified-purchase-explained',
            'title'        => 'Amazon Verified Purchase Badge: What It Really Means',
            'description'  => 'The verified purchase badge is not foolproof. Learn what it means, how it can be manipulated through refund schemes and discount groups, and why you still need to verify review authenticity.',
            'author_key'   => 'derek-armitage',
            'date'         => '2025-12-25',
            'last_updated' => '2026-01-10',
            'image'        => 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=1200&h=630&q=70',
            'keywords'     => 'verified purchase, amazon badge, review verification, authentic reviews, refund schemes',
            'view'         => 'blog.posts.amazon-verified-purchase-explained',
            'reading_time' => 6,
            'sources'      => [
                'Amazon Seller Central documentation',
                'Amazon Community Guidelines',
                'FTC enforcement actions on fake reviews',
            ],
        ],
        [
            'slug'         => 'review-manipulation-tactics-2025',
            'title'        => 'Review Manipulation Tactics Sellers Use in 2025',
            'description'  => 'Discover the latest review manipulation tactics including refund schemes, review swapping, discount groups, and AI farms that bypass Amazon detection. Updated for 2025.',
            'author_key'   => 'research-team',
            'date'         => '2025-12-26',
            'last_updated' => '2026-01-10',
            'image'        => 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&h=630&q=70',
            'keywords'     => 'review manipulation, seller tactics, fake review schemes, amazon fraud, discount groups',
            'view'         => 'blog.posts.review-manipulation-tactics-2025',
            'reading_time' => 9,
            'sources'      => [
                'FTC enforcement actions 2023-2024',
                'Amazon anti-manipulation reports',
                'Consumer Reports investigations',
            ],
        ],
        [
            'slug'         => 'ai-generated-reviews-detection',
            'title'        => 'AI-Generated Reviews: How to Detect ChatGPT and GPT-4 Fake Reviews',
            'description'  => 'AI tools like ChatGPT are creating sophisticated fake reviews. Learn the linguistic patterns, structural tells, and detection methods to identify AI-generated content.',
            'author_key'   => 'derek-armitage',
            'date'         => '2025-12-26',
            'last_updated' => '2026-01-10',
            'image'        => 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=1200&h=630&q=70',
            'keywords'     => 'ai reviews, chatgpt reviews, gpt-4 fake reviews, ai detection, machine learning, nlp',
            'view'         => 'blog.posts.ai-generated-reviews-detection',
            'reading_time' => 8,
            'sources'      => [
                'OpenAI documentation on AI text characteristics',
                'Academic papers on AI text detection',
                'Natural Language Processing research',
            ],
        ],
        [
            'slug'         => 'amazon-review-analysis-tool-guide',
            'title'        => 'How Amazon Review Analysis Tools Work: Behind the Scenes',
            'description'  => 'Learn how review analysis tools like SMART SHIELD UI detect fake reviews using AI, pattern recognition, timing analysis, and statistical methods across thousands of products.',
            'author_key'   => 'derek-armitage',
            'date'         => '2025-12-27',
            'last_updated' => '2026-01-10',
            'image'        => 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&h=630&q=70',
            'keywords'     => 'review analysis tools, fake review detection, ai analysis, product research, nlp',
            'view'         => 'blog.posts.amazon-review-analysis-tool-guide',
            'reading_time' => 10,
            'sources'      => [
                'SMART SHIELD UI open-source methodology',
                'Machine learning documentation',
                'Statistical analysis methods',
            ],
        ],
        [
            'slug'         => 'fake-review-industry-exposed',
            'title'        => 'The Fake Review Industry: A $15 Billion Problem',
            'description'  => 'Inside look at the fake review industry including review farms, automation tools, account marketplaces, and the economics behind review manipulation globally.',
            'author_key'   => 'research-team',
            'date'         => '2025-12-27',
            'last_updated' => '2026-01-10',
            'image'        => 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=1200&h=630&q=70',
            'keywords'     => 'fake review industry, review farms, review fraud economics, amazon manipulation, account marketplace',
            'view'         => 'blog.posts.fake-review-industry-exposed',
            'reading_time' => 9,
            'sources'      => [
                'World Economic Forum estimates on fake reviews',
                'FTC enforcement data',
                'Academic research on review fraud economics',
            ],
        ],
        [
            'slug'         => 'amazon-vine-program-explained',
            'title'        => 'Amazon Vine Program: Legitimate Reviews or Hidden Bias?',
            'description'  => 'Understanding Amazon Vine program, how it works, implicit bias in free product reviews, and whether Vine reviews are more trustworthy than regular customer reviews.',
            'author_key'   => 'derek-armitage',
            'date'         => '2025-12-28',
            'last_updated' => '2026-01-10',
            'image'        => 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1200&h=630&q=70',
            'keywords'     => 'amazon vine, vine reviews, product testing, review bias, amazon program, vine voice',
            'view'         => 'blog.posts.amazon-vine-program-explained',
            'reading_time' => 7,
            'sources'      => [
                'Amazon Vine program documentation',
                'Academic studies on reciprocity bias',
                'Consumer behavior research',
            ],
        ],
        [
            'slug'         => 'review-timing-patterns-analysis',
            'title'        => 'Review Timing Patterns: The Hidden Signal of Fake Reviews',
            'description'  => 'How to analyze review timing patterns to identify coordinated fake review campaigns versus organic customer feedback. Statistical methods and real examples.',
            'author_key'   => 'derek-armitage',
            'date'         => '2025-12-28',
            'last_updated' => '2026-01-10',
            'image'        => 'https://images.unsplash.com/photo-1526378722484-bd91ca387e72?auto=format&fit=crop&w=1200&h=630&q=70',
            'keywords'     => 'review timing, pattern analysis, fake review detection, review campaigns, statistical analysis',
            'view'         => 'blog.posts.review-timing-patterns-analysis',
            'reading_time' => 8,
            'sources'      => [
                'Statistical analysis methodology',
                'Time series analysis research',
                'SMART SHIELD UI detection algorithms',
            ],
        ],
        [
            'slug'         => 'safe-amazon-shopping-guide',
            'title'        => 'Safe Amazon Shopping Guide: 7 Steps to Avoid Fake Products',
            'description'  => 'Complete guide to safe Amazon shopping including review analysis, seller verification, price checking, product research strategies, and scam avoidance techniques.',
            'author_key'   => 'research-team',
            'date'         => '2025-12-29',
            'last_updated' => '2026-01-10',
            'image'        => 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=1200&h=630&q=70',
            'keywords'     => 'safe shopping, amazon tips, avoid scams, product research, consumer protection, online safety',
            'view'         => 'blog.posts.safe-amazon-shopping-guide',
            'reading_time' => 7,
            'sources'      => [
                'FTC consumer protection guidelines',
                'Better Business Bureau recommendations',
                'Consumer Reports buying guides',
            ],
        ],
        [
            'slug'         => 'building-null-fake-open-source',
            'title'        => 'Building SMART SHIELD UI: Why We Made It Open Source',
            'description'  => 'The story behind building SMART SHIELD UI, our technology stack, design decisions, accuracy testing, and why we chose to make it open source and free for everyone.',
            'author_key'   => 'derek-armitage',
            'date'         => '2025-12-30',
            'last_updated' => '2026-01-10',
            'image'        => 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&h=630&q=70',
            'keywords'     => 'open source, SMART SHIELD UI, review analysis, laravel, ai detection, transparency',
            'view'         => 'blog.posts.building-null-fake-open-source',
            'reading_time' => 9,
            'sources'      => [
                'Open Source Initiative principles',
                'Laravel framework documentation',
                'Machine learning best practices',
            ],
        ],
        // New blog posts for AdSense compliance
        [
            'slug'         => 'ftc-fake-review-regulations-2025',
            'title'        => 'FTC Fake Review Regulations: What Consumers Need to Know in 2025',
            'description'  => 'Comprehensive guide to FTC regulations on fake reviews, recent enforcement actions, consumer rights, and how to report fraudulent review practices to authorities.',
            'author_key'   => 'research-team',
            'date'         => '2026-01-05',
            'last_updated' => '2026-01-10',
            'image'        => 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=1200&h=630&q=70',
            'keywords'     => 'ftc regulations, fake reviews law, consumer rights, review fraud enforcement, ftc guidelines',
            'view'         => 'blog.posts.ftc-fake-review-regulations-2025',
            'reading_time' => 10,
            'sources'      => [
                'Federal Trade Commission official guidelines',
                'FTC v. Roomster Corp (2023) case',
                'FTC Endorsement Guides 2023 update',
                'Consumer Financial Protection Bureau',
            ],
        ],
        [
            'slug'         => 'amazon-counterfeit-products-guide',
            'title'        => 'How to Identify Counterfeit Products on Amazon: Complete Guide',
            'description'  => 'Learn to identify counterfeit and knockoff products on Amazon including packaging red flags, seller verification, brand registry, and reporting procedures.',
            'author_key'   => 'derek-armitage',
            'date'         => '2026-01-06',
            'last_updated' => '2026-01-10',
            'image'        => 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=1200&h=630&q=70',
            'keywords'     => 'counterfeit products, amazon fakes, knockoff identification, brand verification, product authenticity',
            'view'         => 'blog.posts.amazon-counterfeit-products-guide',
            'reading_time' => 9,
            'sources'      => [
                'Amazon Brand Registry documentation',
                'U.S. Customs and Border Protection counterfeit reports',
                'GAO reports on e-commerce counterfeits',
                'Anti-Counterfeiting Trade Agreement',
            ],
        ],
        [
            'slug'         => 'review-analysis-methodology-explained',
            'title'        => 'Our Review Analysis Methodology: How SMART SHIELD UI Detects Fake Reviews',
            'description'  => 'Detailed explanation of SMART SHIELD UI\'s review analysis methodology including NLP techniques, statistical models, machine learning approaches, and accuracy metrics.',
            'author_key'   => 'derek-armitage',
            'date'         => '2026-01-07',
            'last_updated' => '2026-01-10',
            'image'        => 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&h=630&q=70',
            'keywords'     => 'review analysis methodology, nlp, machine learning, fake review detection, statistical analysis',
            'view'         => 'blog.posts.review-analysis-methodology-explained',
            'reading_time' => 12,
            'sources'      => [
                'Natural Language Processing fundamentals',
                'Statistical hypothesis testing methodology',
                'Machine learning classification techniques',
                'SMART SHIELD UI open-source codebase',
            ],
        ],
        [
            'slug'         => 'amazon-seller-fraud-warning-signs',
            'title'        => 'Amazon Seller Fraud: 12 Warning Signs to Watch For',
            'description'  => 'Identify fraudulent Amazon sellers before you buy. Learn the warning signs including account age, feedback manipulation, pricing tactics, and shipping red flags.',
            'author_key'   => 'research-team',
            'date'         => '2026-01-08',
            'last_updated' => '2026-01-10',
            'image'        => 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?auto=format&fit=crop&w=1200&h=630&q=70',
            'keywords'     => 'amazon seller fraud, scam sellers, seller verification, marketplace safety, buyer protection',
            'view'         => 'blog.posts.amazon-seller-fraud-warning-signs',
            'reading_time' => 8,
            'sources'      => [
                'Amazon Seller Central policies',
                'BBB complaint data on marketplace sellers',
                'FTC marketplace fraud reports',
                'Consumer Protection Bureau guidelines',
            ],
        ],
        [
            'slug'         => 'review-authenticity-research-findings',
            'title'        => 'Our Research: Analyzing 40,000 Amazon Products for Review Authenticity',
            'description'  => 'Key findings from our analysis of 40,000+ Amazon products including fake review prevalence by category, manipulation tactics by region, and trends over time.',
            'author_key'   => 'research-team',
            'date'         => '2026-01-09',
            'last_updated' => '2026-01-10',
            'image'        => 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1200&h=630&q=70',
            'keywords'     => 'research findings, fake review statistics, amazon analysis, review fraud data, consumer research',
            'view'         => 'blog.posts.review-authenticity-research-findings',
            'reading_time' => 11,
            'sources'      => [
                'SMART SHIELD UI internal analysis database',
                'Comparative industry studies',
                'Academic research on online reviews',
                'E-commerce market research reports',
            ],
        ],
        [
            'slug'         => 'amazon-choice-badge-explained',
            'title'        => 'Amazon\'s Choice Badge: What It Really Means and Why It Can Mislead',
            'description'  => 'The Amazon\'s Choice badge appears trustworthy but is algorithmically assigned without quality verification. Learn what triggers the badge, its limitations, and why you shouldn\'t rely on it alone.',
            'author_key'   => 'derek-armitage',
            'date'         => '2026-01-12',
            'last_updated' => '2026-01-12',
            'image'        => 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=1200&h=630&q=70',
            'keywords'     => 'amazon choice, amazon badge, product recommendations, shopping tips, amazon algorithm, consumer protection',
            'view'         => 'blog.posts.amazon-choice-badge-explained',
            'reading_time' => 7,
            'sources'      => [
                'Amazon Seller Central documentation',
                'Consumer Reports investigations',
                'BuzzFeed News Amazon Choice investigation',
                'Wall Street Journal marketplace reporting',
            ],
        ],
        [
            'slug'         => 'browser-extensions-fake-review-detection',
            'title'        => 'Browser Extensions for Spotting Fake Reviews: A Practical Guide',
            'description'  => 'Review the landscape of browser extensions that help detect fake Amazon reviews. Learn how they work, their accuracy, privacy considerations, and how to use them effectively.',
            'author_key'   => 'research-team',
            'date'         => '2026-01-15',
            'last_updated' => '2026-01-15',
            'image'        => 'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?auto=format&fit=crop&w=1200&h=630&q=70',
            'keywords'     => 'browser extension, chrome extension, fake review detector, review analysis tool, shopping assistant, consumer tools',
            'view'         => 'blog.posts.browser-extensions-fake-review-detection',
            'reading_time' => 8,
            'sources'      => [
                'Chrome Web Store extension policies',
                'Privacy analysis of shopping extensions',
                'Consumer advocacy tool comparisons',
                'Browser extension security research',
            ],
        ],
        [
            'slug'         => 'amazon-listing-hijacking-explained',
            'title'        => 'Product Listing Hijacking: When Good Products Get Flooded with Fake Reviews',
            'description'  => 'Listing hijacking is a sophisticated fraud where bad actors attach counterfeit products to legitimate listings. Learn how it works, how to identify hijacked listings, and protect yourself.',
            'author_key'   => 'derek-armitage',
            'date'         => '2026-01-18',
            'last_updated' => '2026-01-18',
            'image'        => 'https://images.unsplash.com/photo-1586953208448-b95a79798f07?auto=format&fit=crop&w=1200&h=630&q=70',
            'keywords'     => 'listing hijacking, amazon fraud, product scam, seller manipulation, counterfeit listings, marketplace fraud',
            'view'         => 'blog.posts.amazon-listing-hijacking-explained',
            'reading_time' => 9,
            'sources'      => [
                'Amazon Seller Central anti-hijacking policies',
                'E-commerce fraud investigation reports',
                'Brand protection case studies',
                'FTC marketplace fraud enforcement',
            ],
        ],
        [
            'slug'         => 'international-amazon-fake-review-patterns',
            'title'        => 'International Amazon Marketplaces: How Fake Review Patterns Vary by Region',
            'description'  => 'Fake review tactics differ across Amazon\'s global marketplaces. Analysis of patterns in US, UK, Germany, Japan, and other regions reveals distinct manipulation strategies and cultural factors.',
            'author_key'   => 'research-team',
            'date'         => '2026-01-21',
            'last_updated' => '2026-01-21',
            'image'        => 'https://images.unsplash.com/photo-1526778548025-fa2f459cd5c1?auto=format&fit=crop&w=1200&h=630&q=70',
            'keywords'     => 'international amazon, global marketplace, regional reviews, fake review patterns, amazon uk, amazon germany, amazon japan',
            'view'         => 'blog.posts.international-amazon-fake-review-patterns',
            'reading_time' => 10,
            'sources'      => [
                'SMART SHIELD UI cross-regional analysis data',
                'European Consumer Organisation (BEUC) reports',
                'Japan Consumer Affairs Agency findings',
                'International e-commerce research studies',
            ],
        ],
    ],
];
